# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170902_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, default='static/icons/aurora.jpg', upload_to='static/icons'),
        ),
    ]
