# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='reply_date',
            new_name='response_date',
        ),
    ]
