# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_thread_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thread_title',
            new_name='title',
        ),
    ]
