# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20170906_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thread_content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thread_date',
            new_name='posted',
        ),
    ]
