# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20170906_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='author',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='author',
            new_name='poster',
        ),
    ]
