# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20170906_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response_content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response_date',
            new_name='posted',
        ),
    ]
