# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170902_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date joined'),
        ),
    ]
